spring.application.name=compstore

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework.security=DEBUG
spring.jackson.time-zone=Asia/Kolkata
server.port=${PORT:8080}
jwt.secret=/IoUn2lh0X6IdGmW4XBKmCEpoW5nQIgnEmSIyCxNZjIMaR12HutJ24YDmPSdyDuy2izEfVm0Hlk4zBvTF6E0Bw==